DISCOGS_GENRES = {
    'Blues': [
        'Chicago Blues',
        'Country Blues',
        'Delta Blues',
        'East Coast Blues',
        'Electric Blues',
        'Harmonica Blues',
        'Jump Blues',
        'Louisiana Blues',
        'Modern Electric Blues',
        'Piano Blues',
        'Piedmont Blues',
        'Texas Blues',
    ],
    'Brass & Military': [
        'Brass Band',
        'Marches',
        'Military',
        'Pipe & Drum',
    ],
    'Children\'s': [
        'Educational',
        'Nursery Rhymes',
        'Story',
    ],
    'Classical': [
        'Baroque',
        'Classical',
        'Contemporary',
        'Early',
        'Medieval',
        'Modern',
        'Neo-Classical',
        'Neo-Romantic',
        'Post-Modern',
        'Renaissance',
        'Romantic',
    ],
    'Electronic': [
        'Abstract',
        'Experimental',
        'Musique Concrète',
        'Acid (D)',
        'Ambient',
        'Dark Ambient',
        'New Age',
        'Downtempo',
        'Acid Jazz',
        'Big Beat',
        'Breakbeat',
        'Breaks',
        'Freestyle',
        'Jazzdance',
        'Broken Beat',
        'Glitch',
        'Disco',
        'Italo-Disco',
        'Italodance',
        'Drum n Bass',
        'Dubstep',
        'Jumpstyle',
        'Jungle',
        'Dub (D)',
        'EBM',
        'IDM',
        'Industrial',
        'New Beat',
        'Electro',
        'Synth-pop',
        'Chiptune',
        'Ghetto (D)',
        'Hardcore',
        'Breakcore',
        'Gabber',
        'Happy Hardcore',
        'Hardstyle',
        'Speedcore',
        'Hi NRG',
        'Hip Hop',
        'Illbient',
        'Trip Hop',
        'Leftfield',
        'House',
        'Acid House',
        'Deep House',
        'Euro House',
        'Garage House',
        'Hard House',
        'Hip-House',
        'Progressive House',
        'Tech House',
        'Tribal House',
        'Krautrock',
        'Latin (D)',
        'Modern Classical',
        'Neofolk',
        'New Wave',
        'Darkwave',
        'Drone',
        'Noise',
        'Power Electronics',
        'Rhythmic Noise',
        'Techno',
        'Dub Techno',
        'Future Jazz',
        'Makina',
        'Minimal',
        'Tribal',
        'Trance',
        'Goa Trance',
        'Hard Trance',
        'Progressive Trance',
        'Psy-Trance',
        'Grime',
        'Speed Garage',
        'UK Garage',
    ],
    'Folk, World, & Country': [
        'Country',
        'Bluegrass',
        'Cajun',
        'Honky Tonk',
        'Zouk',
        'Zydeco',
        'Folk',
    ],
    'Funk / Soul': [
        'Afrobeat',
        'Disco',
        'Funk',
        'Free Funk',
        'Bayou Funk',
        'P.Funk',
        'Gogo',
        'Gospel',
        'Neo Soul',
        'New Jack Swing',
        'Psychedelic',
        'Rhythm & Blues',
        'Soul',
        'Swingbeat',
    ],
    'Hip Hop': [
        'Bass Music',
        'Bounce',
        'Britcore',
        'Conscious',
        'Crunk',
        'Cut-up/DJ',
        'DJ Battle Tool',
        'Electro',
        'Gangsta',
        'Go-Go',
        'Grime',
        'Horrorcore',
        'Hyphy',
        'Instrumental',
        'Kwaito',
        'Pop Rap',
        'Ragga HipHop',
        'RnB/Swing',
        'Screw',
        'Thug Rap',
        'Trip Hop',
    ],
    'Jazz': [
        'Afro-Cuban Jazz',
        'Bossa Nova',
        'Latin Jazz',
        'Afrobeat',
        'Big Band',
        'Dixieland',
        'Ragtime',
        'Swing',
        'Bop',
        'Hard Bop',
        'Post Bop',
        'Contemporary Jazz',
        'Cool Jazz',
        'Easy Listening',
        'Smooth Jazz',
        'Free Improvisation',
        'Free Jazz',
        'Fusion',
        'Soul-Jazz',
        'Gypsy Jazz',
        'Jazz-Funk',
        'Jazz-Rock',
        'Modal',
        'Space-Age',
    ],
    'Latin': [
        'Afro-Cuban',
        'Beguine',
        'Bolero',
        'Cha-Cha',
        'Charanga',
        'Conjunto',
        'Cubano',
        'Danzon',
        'Descarga',
        'Guaguancó',
        'Mambo',
        'Pachanga',
        'Rumba',
        'Salsa',
        'Son',
        'Sonero',
        'Timba',
        'Bachata',
        'Batucada',
        'Bossanova',
        'Lambada',
        'Samba',
        'Boogaloo',
        'Compas',
        'Corrido',
        'Cuatro',
        'Cumbia',
        'Vallenato',
        'Flamenco',
        'Forro',
        'Jibaro',
        'MPB',
        'Merengue',
        'Música Criolla',
        'Vals Criollo',
        'Polca Criolla',
        'Mariachi',
        'Marimba',
        'Norteño',
        'Ranchera',
        'Tejano',
        'Nueva Cancion',
        'Nueva Trova',
        'Trova',
        'Plena',
        'Quechua',
        'Reggaeton',
        'Tango',
    ],
    'Non-Music': [
        'Audiobook',
        'Comedy',
        'Dialogue',
        'Education',
        'Field Recording',
        'Interview',
        'Monolog',
        'Movie Effects',
        'Poetry',
        'Political',
        'Promotional',
        'Public Service Announcement',
        'Radioplay',
        'Religious',
        'Sermon',
        'Special Effects',
        'Speech',
        'Spoken Word',
        'Technical',
        'Therapy',
    ],
    'Pop': [
        'Ballad',
        'Bollywood',
        'Chanson',
        'Enka',
        'Europop',
        'J-pop',
        'Karaoke',
        'Music Hall',
        'Novelty',
        'Parody',
        'Schlager',
        'Vocal',
    ],
    'Rock': [
        'Acoustic',
        'Alternative Rock',
        'Arena Rock',
        'Art Rock',
        'Blues Rock',
        'Country Rock',
        'Classic Rock',
        'Folk Rock',
        'Garage Rock',
        'Goth Rock',
        'Glam',
        'Hard Rock',
        'Indie Rock',
        'Math Rock',
        'Pop Rock',
        'Post Rock',
        'Prog Rock',
        'Psychedelic Rock',
        'Southern Rock',
        'Space Rock',
        'Soft Rock',
        'Stoner Rock',
        'Symphonic Rock',
        'Avantgarde',
        'Brit Pop',
        'Doo Wop',
        'Heavy Metal',
        'Black Metal',
        'Death Metal',
        'Doom Metal',
        'Nu Metal',
        'Viking Metal',
        'New Wave',
        'Funk Metal',
        'Speed Metal',
        'Emo',
        'Ethereal',
        'Experimental',
        'Grindcore',
        'Grunge',
        'Hardcore',
        'Noise',
        'Thrash',
        'Industrial',
        'Lo-Fi',
        'Lounge',
        'Power Pop',
        'Shoegaze',
        'Shoegazer',
        'Mod',
        'Neofolk',
        'Oi',
        'Punk',
        'Parody',
        'Rock & Roll',
        'Rockabilly',
        'Psychobilly',
        'Skiffle',
        'Rocksteady',
        'Ska',
        'Surf',
    ],
    'Reggae': [
        'Calypso',
        'Soca',
        'Steel Band',
        'Dancehall',
        'Ragga',
        'Dub',
        'Dub Poetry',
        'Junkanoo',
        'Mento',
        'Reggae',
        'Lovers Rock',
        'Reggae Gospel',
        'Reggae-Pop',
        'Roots Reggae',
        'Rapso',
        'Rocksteady',
        'Ska',
    ],
    'Stage & Screen': [
        'Musical',
        'Score',
        'Soundtrack',
        'Theme',
    ],
}
